name: '[ BUILD ] Build Project (Java/Maven)'

on:
  workflow_dispatch:
    inputs:
      release_build:
        description: 'toggles an release-build, by default false'
        type: boolean
        default: false
        required: false
      build_version:
        description: 'The version to build and deploy'
        type: string
        required: true
        default: '0-SNAPSHOT'
  workflow_call:
    inputs:
      release_build:
        description: 'toggles an release-build, by default false'
        type: boolean
        default: false
        required: false
      build_version:
        description: 'The version to build and deploy'
        type: string
        required: false
        default: '0-SNAPSHOT'
    outputs:
      build_artifact_id:
        description: 'The id of the uploaded build artifacts.'
        value: ${{ jobs.Build.outputs.build_artifacts_id}}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_VERSION: ${{ inputs.build_version != '' && inputs.build_version || '0-SNAPSHOT' }}

jobs:
  Validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: maven/actions/wrapper-validation@v4